server:
  port: 8080
  servlet:
    context-path: /tiny-url

app:
  base-url: http://localhost:8080/tiny-url

spring:
  application:
    name: tiny-url-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET}
  access-expiry: ${ACCESS_EXPIRATION}
